### ISSUE TITLE
Edge and IE Support

### ISSUE THREAD

**Issue by gavinhenderson** [Deep-See/DeepSee-Core#2]

**Comment by AdamHirst** [comment]
Definitely something to look into. According to https://docs.microsoft.com/en-us/microsoft-edge/extensions : 
"Microsoft Edge supports a new HTML, JavaScript and CSS based extension model. This new model is Chrome-compatible which means that existing Chrome extension developers will be able to migrate their extensions to Microsoft Edge with minimal changes."

Also subject to support on IE/Edge for certain features. Will add to readme, probably further on in the roadmap compared to Chrome/Firefox support.
